README.md
site/makedoc.cwl
website.sh

Also tweak makedoc and website.sh

Add link to cwldep.

---

site/cwlsite-draft3-schemas.json
site/cwlsite-v1.0.0-schemas.json
site/cwlsite-v1.1.0-dev1-schemas.yaml
site/cwlsite.cwl
site/inheritance.cwl

Refs https://github.com/common-workflow-language/common-workflow-language/issues/179

Render inheritance graph

---

README.md

Added badge and changed from alpha to beta

Updated status for AWE

---

README.md

add researchobjects.org/CWLProv

---

README.md

Links to https://github.com/Duke-GCB/calrissian

Adds calrissian to in-development implementations

---

README.md

StreamFlow (https://streamflow.di.unito.it/) is a CWL-based WMS addressing hybrid Cloud-HPC infrastructures.
Currently, support for CWL 1.2 is under development: an almost full compliance with the standard is in plans, but we are still missing some functionalities (e.g. format checking and conditions)

Added StreamFlow WMS to partial implementations

---

content/_includes/home/implementations.html

I noticed Magnum had a hanging )

Fix typo - remove ) after Magnum in Implementations

---

content/_includes/home/contributers-and-governance.html

I have been working at the [National Institute of Genetics](https://www.nig.ac.jp/nig/) (NIG) since this April!

Change affiliaton of Tomoya Tanjo

---

content/tools.md

Mention the Common Workflow Language Lab (Fixes #103 )

refresh ecosystem lists by recent releases

---

content/404.html

Replacing the auto-generated 404 page with one that matches the new site.

Add 404 page

---

content/_data/user-gallery.yml

Set the main ACROSS link to their homepage

---

.github/ISSUE_TEMPLATE/user-gallery-nomination.md

add issue template for user gallery nomination

---

content/gallery.html

User Gallery: nominations for additional entries are welcome

---

content/_config.yml
content/_config_local.yml
content/_config_staging.yml
content/_includes/head.html

Note: Not ready for merge yet (doing a quick test, and then I will re-push)

SEO & Environment debug

---

content/code-of-conduct.md

Pulling in most recent update from https://github.com/common-workflow-language/common-workflow-language/blob/main/CODE_OF_CONDUCT.md

Update Code of Conduct (switched Gitter to Matrix)

---

content/_sass/partials/home/_mini-gallery.scss
content/gallery.html

Fixes the Elixir logo background in the home page mini gallery.

Elixir logo fix

---

content/features.md

This solves issue [ #149](https://github.com/common-workflow-language/cwl-website/issues/149)

fix: minor typo on website

---

site/cwl-jekyll.cwl
site/cwlsite.cwl
site/inheritance.cwl
site/linkchecker.cwl
site/makecontext.cwl
site/makedoc.cwl
site/makerdfs.cwl
site/mergesecondary.cwl

upgrade site/*.cwl to cwlVersion: v1.2

---

content/implementations.md

Add mentioned in https://github.com/crim-ca/weaver/issues/381#issuecomment-1574205239

Add Weaver to the list of partial CWL implementations

---

content/_includes/home/video-player.html
content/assets/video/subtitles/ct.vtt
content/assets/video/subtitles/de.vtt
content/assets/video/subtitles/es.vtt
content/assets/video/subtitles/nl.vtt

Thank you to the members of the "Facilitating the “Great Bake Off” of Bioinformatics Workflows" 2022 workshop who contributed these translations!

add spanish, catalan, dutch, & german subtitles

---

content/features.md

Carole reported she couldn't refind the link, so make it more descriptive than "very popular"

Make link to Existing Workflow Systems more obvious

---

.gitignore

When compiling / building website locally, end up with a few thousand cache files

Add repo git ignore file

---

.github/ISSUE_TEMPLATE/user-gallery-nomination.md
content/_data/navigation.yml
content/_data/user-gallery.yml

user gallery: add the Cherenkov Telescope Array Observatory

---

.github/ISSUE_TEMPLATE/user-gallery-nomination.md
content/_data/navigation.yml
content/_data/user-gallery.yml

This commit adds a `High-Performance Computing` section for CWL users and projects.

Add High-Performance Computing section
